# Generated by Django 6.1.1 on 2026-09-12 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='videos/original/')),
                ('output_format', models.CharField(max_length=10)),
                ('resolution', models.CharField(max_length=10)),
                ('converted_file', models.FileField(blank=True, null=True, upload_to='videos/converted/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_conversions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
